social_channels:
  reddit:
    # - "username"
  twitter:
    # - "username"
  instagram:
    # - "username"

auth:
  slack:
    webhook_url: ""
  twitter:
    api_key: ""
    secret_key: ""
  instagram:
    username: ""
    password: ""

app:
  sleep_time: 2000
